{"uuid": "015a8c50-2c7d-48d9-a7c8-d78fe6274e88", "children": ["73309bc2-81ed-4617-84d7-9327e36530b9"], "befores": [{"name": "get_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status\nfrom disconnected: received Inspector.detached event\n  (Session info: chrome=94.0.4606.81)\n\n", "trace": "  File \"c:\\users\\shafaat65\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\shafaat65\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\shafaat65\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\shafaat65\\PycharmProjects\\POMProject\\TestCases\\conftest.py\", line 43, in get_browser\n    driver.get(configreader.readConfig(\"basicinfo\",\"testurl\"))\n  File \"c:\\users\\shafaat65\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\shafaat65\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\shafaat65\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1635002950674, "stop": 1635002959491}], "start": 1635002950674, "stop": 1635002959686}